import { StyleSheet } from 'react-native';

import type { AppTheme } from '../theme';
import { ENTRY_ROW_HEIGHT } from './workspacePickerHelpers';

export const createWorkspacePickerBrowserStyles = (theme: AppTheme) => ({
  workspaceRow: {
    width: '100%' as const,
    minHeight: 64,
    paddingHorizontal: theme.spacing.xs,
    paddingVertical: theme.spacing.sm,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: theme.spacing.sm + 2,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.borderLight,
  },
  folderRow: {
    width: '100%' as const,
    height: ENTRY_ROW_HEIGHT,
    paddingHorizontal: theme.spacing.lg,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: theme.spacing.sm + 2,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.borderLight,
  },
  rowLast: {
    borderBottomWidth: 0,
  },
  rowIcon: {
    width: 30,
    height: 30,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  rowCopy: {
    flex: 1,
    minWidth: 0,
  },
  rowTitle: {
    ...theme.typography.body,
    color: theme.colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600' as const,
  },
  rowSubtitle: {
    ...theme.typography.caption,
    marginTop: 3,
    color: theme.colors.textMuted,
    fontSize: 10,
    lineHeight: 13,
  },
  rowPath: {
    ...theme.typography.mono,
    fontSize: 9,
    lineHeight: 12,
  },
  rowAccessory: {
    minWidth: 28,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'flex-end' as const,
    gap: 6,
  },
  rowMeta: {
    ...theme.typography.caption,
    color: theme.colors.textMuted,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '500' as const,
  },
  browserToolbar: {
    minHeight: 45,
    paddingHorizontal: theme.spacing.md,
    position: 'relative' as const,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.borderLight,
  },
  backButton: {
    width: 92,
    minWidth: 0,
    minHeight: 44,
    zIndex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
  },
  backButtonText: {
    ...theme.typography.body,
    flexShrink: 1,
    color: theme.colors.accent,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '500' as const,
  },
  browserTitle: {
    ...theme.typography.headline,
    position: 'absolute' as const,
    right: 100,
    left: 100,
    color: theme.colors.textPrimary,
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '600' as const,
    textAlign: 'center' as const,
  },
  browserSearchWrap: {
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.sm,
    paddingBottom: 7,
  },
  searchField: {
    height: 36,
    paddingHorizontal: theme.spacing.sm + 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 7,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.bgInput,
  },
  searchInput: {
    ...theme.typography.body,
    flex: 1,
    paddingVertical: 0,
    color: theme.colors.textPrimary,
    fontSize: 13,
    lineHeight: 18,
  },
  location: {
    minHeight: 48,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: 8,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: theme.spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.borderLight,
  },
  locationCopy: {
    flex: 1,
    minWidth: 0,
  },
  locationTitle: {
    ...theme.typography.body,
    color: theme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600' as const,
  },
  locationPath: {
    ...theme.typography.mono,
    marginTop: 2,
    color: theme.colors.textMuted,
    fontSize: 9,
    lineHeight: 12,
  },
  errorText: {
    ...theme.typography.caption,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.sm,
    color: theme.colors.error,
    fontSize: 11,
    lineHeight: 15,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.borderLight,
  },
  noticeText: {
    ...theme.typography.caption,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.sm,
    color: theme.colors.textMuted,
    fontSize: 11,
    lineHeight: 15,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.borderLight,
  },
  entryList: {
    flex: 1,
    minHeight: 0,
  },
  entryListContent: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderLight,
  },
  entryListEmptyContent: {
    flexGrow: 1,
  },
  emptyState: {
    flex: 1,
    minHeight: 132,
    paddingHorizontal: theme.spacing.xl,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: theme.spacing.sm,
  },
  emptyStateText: {
    ...theme.typography.body,
    color: theme.colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center' as const,
  },
  browserFooter: {
    paddingTop: 9,
    paddingHorizontal: theme.spacing.lg,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderLight,
    backgroundColor: theme.colors.bgElevated,
  },
  chooseButton: {
    width: '100%' as const,
    minHeight: 47,
    paddingHorizontal: theme.spacing.lg,
    borderRadius: theme.radius.md,
    borderCurve: 'continuous' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: theme.colors.accent,
  },
  chooseButtonPressed: {
    backgroundColor: theme.colors.accentPressed,
  },
  chooseButtonText: {
    ...theme.typography.body,
    color: theme.colors.accentText,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '700' as const,
  },
});
