// @generated by scripts/generate-agui-bindings.mjs from @ag-ui/core@0.0.57.
// Source sha256: 2292a14d101c9d61691a5ab4756504b196c4c8a1726bbfa54324daee8d6b9d10. Do not edit by hand.
// Example code that deserializes and serializes the model.
// extern crate serde;
// #[macro_use]
// extern crate serde_derive;
// extern crate serde_json;
//
// use generated_module::AgUiEvent;
//
// fn main() {
//     let json = r#"{"answer": 42}"#;
//     let model: AgUiEvent = serde_json::from_str(&json).unwrap();
// }

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgUiEvent {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) message_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) name: Option<String>,

    pub(crate) raw_event: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) role: Option<AgUiEventRole>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) timestamp: Option<f64>,

    #[serde(rename = "type")]
    pub(crate) ag_ui_event_type: AgUiEventType,

    pub(crate) delta: Option<Delta>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) title: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) parent_message_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) tool_call_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) tool_call_name: Option<String>,

    pub(crate) content: Option<AgUiEventContent>,

    pub(crate) snapshot: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) messages: Option<Vec<Message>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) activity_type: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) replace: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) patch: Option<Vec<Option<serde_json::Value>>>,

    pub(crate) event: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) source: Option<String>,

    pub(crate) value: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) input: Option<Input>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) parent_run_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) run_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) thread_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) outcome: Option<Outcome>,

    pub(crate) result: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) code: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) message: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) step_name: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) encrypted_value: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) entity_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) subtype: Option<Subtype>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum AgUiEventType {
    #[serde(rename = "ACTIVITY_DELTA")]
    ActivityDelta,

    #[serde(rename = "ACTIVITY_SNAPSHOT")]
    ActivitySnapshot,

    Custom,

    #[serde(rename = "MESSAGES_SNAPSHOT")]
    MessagesSnapshot,

    Raw,

    #[serde(rename = "REASONING_ENCRYPTED_VALUE")]
    ReasoningEncryptedValue,

    #[serde(rename = "REASONING_END")]
    ReasoningEnd,

    #[serde(rename = "REASONING_MESSAGE_CHUNK")]
    ReasoningMessageChunk,

    #[serde(rename = "REASONING_MESSAGE_CONTENT")]
    ReasoningMessageContent,

    #[serde(rename = "REASONING_MESSAGE_END")]
    ReasoningMessageEnd,

    #[serde(rename = "REASONING_MESSAGE_START")]
    ReasoningMessageStart,

    #[serde(rename = "REASONING_START")]
    ReasoningStart,

    #[serde(rename = "RUN_ERROR")]
    RunError,

    #[serde(rename = "RUN_FINISHED")]
    RunFinished,

    #[serde(rename = "RUN_STARTED")]
    RunStarted,

    #[serde(rename = "STATE_DELTA")]
    StateDelta,

    #[serde(rename = "STATE_SNAPSHOT")]
    StateSnapshot,

    #[serde(rename = "STEP_FINISHED")]
    StepFinished,

    #[serde(rename = "STEP_STARTED")]
    StepStarted,

    #[serde(rename = "TEXT_MESSAGE_CHUNK")]
    TextMessageChunk,

    #[serde(rename = "TEXT_MESSAGE_CONTENT")]
    TextMessageContent,

    #[serde(rename = "TEXT_MESSAGE_END")]
    TextMessageEnd,

    #[serde(rename = "TEXT_MESSAGE_START")]
    TextMessageStart,

    #[serde(rename = "THINKING_END")]
    ThinkingEnd,

    #[serde(rename = "THINKING_START")]
    ThinkingStart,

    #[serde(rename = "THINKING_TEXT_MESSAGE_CONTENT")]
    ThinkingTextMessageContent,

    #[serde(rename = "THINKING_TEXT_MESSAGE_END")]
    ThinkingTextMessageEnd,

    #[serde(rename = "THINKING_TEXT_MESSAGE_START")]
    ThinkingTextMessageStart,

    #[serde(rename = "TOOL_CALL_ARGS")]
    ToolCallArgs,

    #[serde(rename = "TOOL_CALL_CHUNK")]
    ToolCallChunk,

    #[serde(rename = "TOOL_CALL_END")]
    ToolCallEnd,

    #[serde(rename = "TOOL_CALL_RESULT")]
    ToolCallResult,

    #[serde(rename = "TOOL_CALL_START")]
    ToolCallStart,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AgUiEventContent {
    AnythingMap(HashMap<String, Option<serde_json::Value>>),

    String(String),
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Delta {
    AnythingArray(Vec<Option<serde_json::Value>>),

    String(String),
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Input {
    pub(crate) context: Vec<Context>,

    pub(crate) forwarded_props: Option<serde_json::Value>,

    pub(crate) messages: Vec<Message>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) parent_run_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) resume: Option<Vec<Resume>>,

    pub(crate) run_id: String,

    pub(crate) state: Option<serde_json::Value>,

    pub(crate) thread_id: String,

    pub(crate) tools: Vec<Tool>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Context {
    pub(crate) description: String,

    pub(crate) value: String,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Message {
    pub(crate) content: Option<MessageContent>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) encrypted_value: Option<String>,

    pub(crate) id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) name: Option<String>,

    pub(crate) role: MessageRole,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) tool_calls: Option<Vec<ToolCall>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) error: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) tool_call_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) activity_type: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageContent {
    AnythingMap(HashMap<String, Option<serde_json::Value>>),

    ContentElementArray(Vec<ContentElement>),

    String(String),
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ContentElement {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) text: Option<String>,

    #[serde(rename = "type")]
    pub(crate) content_type: ContentType,

    pub(crate) metadata: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) source: Option<Source>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) data: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) filename: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) mime_type: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) url: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ContentType {
    Audio,

    Binary,

    Document,

    Image,

    Text,

    Video,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Source {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) mime_type: Option<String>,

    #[serde(rename = "type")]
    pub(crate) source_type: SourceType,

    pub(crate) value: String,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SourceType {
    Data,

    Url,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MessageRole {
    Activity,

    Assistant,

    Developer,

    Reasoning,

    System,

    Tool,

    User,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolCall {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) encrypted_value: Option<String>,

    pub(crate) function: Function,

    pub(crate) id: String,

    #[serde(rename = "type")]
    pub(crate) tool_call_type: ToolCallType,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Function {
    pub(crate) arguments: String,

    pub(crate) name: String,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ToolCallType {
    Function,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Resume {
    pub(crate) interrupt_id: String,

    pub(crate) payload: Option<serde_json::Value>,

    pub(crate) status: Status,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Status {
    Cancelled,

    Resolved,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Tool {
    pub(crate) description: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) metadata: Option<HashMap<String, Option<serde_json::Value>>>,

    pub(crate) name: String,

    pub(crate) parameters: Option<serde_json::Value>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Outcome {
    #[serde(rename = "type")]
    pub(crate) outcome_type: OutcomeType,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) interrupts: Option<Vec<Interrupt>>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Interrupt {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) expires_at: Option<String>,

    pub(crate) id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) message: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) metadata: Option<HashMap<String, Option<serde_json::Value>>>,

    pub(crate) reason: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) response_schema: Option<HashMap<String, Option<serde_json::Value>>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) tool_call_id: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OutcomeType {
    Interrupt,

    Success,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgUiEventRole {
    Assistant,

    Developer,

    Reasoning,

    System,

    Tool,

    User,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Subtype {
    Message,

    #[serde(rename = "tool-call")]
    ToolCall,
}
